module Settings
  class TimeZoneOptions
    RUSSIAN_NAMES = {
      "International Date Line West" => "Линия перемены дат (запад)",
      "Midway Island" => "Остров Мидуэй",
      "American Samoa" => "Американское Самоа",
      "Hawaii" => "Гавайи",
      "Alaska" => "Аляска",
      "Pacific Time (US & Canada)" => "Тихоокеанское время (США и Канада)",
      "Tijuana" => "Тихуана",
      "Mountain Time (US & Canada)" => "Горное время (США и Канада)",
      "Arizona" => "Аризона",
      "Chihuahua" => "Чиуауа",
      "Mazatlan" => "Масатлан",
      "Central Time (US & Canada)" => "Центральное время (США и Канада)",
      "Saskatchewan" => "Саскачеван",
      "Guadalajara" => "Гвадалахара",
      "Mexico City" => "Мехико",
      "Monterrey" => "Монтеррей",
      "Central America" => "Центральная Америка",
      "Eastern Time (US & Canada)" => "Восточное время (США и Канада)",
      "Indiana (East)" => "Индиана (восток)",
      "Bogota" => "Богота",
      "Lima" => "Лима",
      "Quito" => "Кито",
      "Atlantic Time (Canada)" => "Атлантическое время (Канада)",
      "Caracas" => "Каракас",
      "Georgetown" => "Джорджтаун",
      "La Paz" => "Ла-Пас",
      "Puerto Rico" => "Пуэрто-Рико",
      "Santiago" => "Сантьяго",
      "Newfoundland" => "Ньюфаундленд",
      "Brasilia" => "Бразилиа",
      "Buenos Aires" => "Буэнос-Айрес",
      "Montevideo" => "Монтевидео",
      "Greenland" => "Гренландия",
      "Mid-Atlantic" => "Срединно-Атлантическое время",
      "Azores" => "Азорские острова",
      "Cape Verde Is." => "Острова Кабо-Верде",
      "Dublin" => "Дублин",
      "Edinburgh" => "Эдинбург",
      "Lisbon" => "Лиссабон",
      "London" => "Лондон",
      "Casablanca" => "Касабланка",
      "Monrovia" => "Монровия",
      "UTC" => "Всемирное координированное время",
      "Belgrade" => "Белград",
      "Bratislava" => "Братислава",
      "Budapest" => "Будапешт",
      "Ljubljana" => "Любляна",
      "Prague" => "Прага",
      "Sarajevo" => "Сараево",
      "Skopje" => "Скопье",
      "Warsaw" => "Варшава",
      "Zagreb" => "Загреб",
      "Brussels" => "Брюссель",
      "Copenhagen" => "Копенгаген",
      "Madrid" => "Мадрид",
      "Paris" => "Париж",
      "Amsterdam" => "Амстердам",
      "Berlin" => "Берлин",
      "Bern" => "Берн",
      "Rome" => "Рим",
      "Stockholm" => "Стокгольм",
      "Vienna" => "Вена",
      "West Central Africa" => "Западная Центральная Африка",
      "Bucharest" => "Бухарест",
      "Cairo" => "Каир",
      "Helsinki" => "Хельсинки",
      "Kyiv" => "Киев",
      "Riga" => "Рига",
      "Sofia" => "София",
      "Tallinn" => "Таллин",
      "Vilnius" => "Вильнюс",
      "Athens" => "Афины",
      "Istanbul" => "Стамбул",
      "Minsk" => "Минск",
      "Jerusalem" => "Иерусалим",
      "Harare" => "Хараре",
      "Pretoria" => "Претория",
      "Kaliningrad" => "Калининград",
      "Moscow" => "Москва",
      "St. Petersburg" => "Санкт-Петербург",
      "Volgograd" => "Волгоград",
      "Samara" => "Самара",
      "Kuwait" => "Кувейт",
      "Riyadh" => "Эр-Рияд",
      "Nairobi" => "Найроби",
      "Baghdad" => "Багдад",
      "Tehran" => "Тегеран",
      "Abu Dhabi" => "Абу-Даби",
      "Muscat" => "Маскат",
      "Baku" => "Баку",
      "Tbilisi" => "Тбилиси",
      "Yerevan" => "Ереван",
      "Kabul" => "Кабул",
      "Ekaterinburg" => "Екатеринбург",
      "Islamabad" => "Исламабад",
      "Karachi" => "Карачи",
      "Tashkent" => "Ташкент",
      "Chennai" => "Ченнаи",
      "Kolkata" => "Калькутта",
      "Mumbai" => "Мумбаи",
      "New Delhi" => "Нью-Дели",
      "Kathmandu" => "Катманду",
      "Astana" => "Астана",
      "Sri Jayawardenepura" => "Шри-Джаяварденепура-Котте",
      "Almaty" => "Алматы",
      "Novosibirsk" => "Новосибирск",
      "Rangoon" => "Янгон",
      "Yangon" => "Янгон",
      "Bangkok" => "Бангкок",
      "Hanoi" => "Ханой",
      "Jakarta" => "Джакарта",
      "Krasnoyarsk" => "Красноярск",
      "Beijing" => "Пекин",
      "Chongqing" => "Чунцин",
      "Hong Kong" => "Гонконг",
      "Urumqi" => "Урумчи",
      "Kuala Lumpur" => "Куала-Лумпур",
      "Singapore" => "Сингапур",
      "Taipei" => "Тайбэй",
      "Perth" => "Перт",
      "Irkutsk" => "Иркутск",
      "Ulaanbaatar" => "Улан-Батор",
      "Seoul" => "Сеул",
      "Osaka" => "Осака",
      "Sapporo" => "Саппоро",
      "Tokyo" => "Токио",
      "Yakutsk" => "Якутск",
      "Darwin" => "Дарвин",
      "Adelaide" => "Аделаида",
      "Canberra" => "Канберра",
      "Melbourne" => "Мельбурн",
      "Sydney" => "Сидней",
      "Brisbane" => "Брисбен",
      "Hobart" => "Хобарт",
      "Vladivostok" => "Владивосток",
      "Guam" => "Гуам",
      "Port Moresby" => "Порт-Морсби",
      "Magadan" => "Магадан",
      "Srednekolymsk" => "Среднеколымск",
      "Solomon Is." => "Соломоновы острова",
      "New Caledonia" => "Новая Каледония",
      "Fiji" => "Фиджи",
      "Kamchatka" => "Камчатка",
      "Marshall Is." => "Маршалловы острова",
      "Auckland" => "Окленд",
      "Wellington" => "Веллингтон",
      "Nuku'alofa" => "Нукуалофа",
      "Tokelau Is." => "Токелау",
      "Chatham Is." => "Острова Чатем",
      "Samoa" => "Самоа"
    }.freeze

    def self.call
      ActiveSupport::TimeZone.all
                             .sort_by { |zone| [zone.utc_offset, localized_name(zone).downcase] }
                             .map { |zone| [label_for(zone), zone.name] }
    end

    def self.label_for(zone)
      "(UTC#{zone.formatted_offset}) #{localized_name(zone)}"
    end

    def self.localized_name(zone)
      RUSSIAN_NAMES.fetch(zone.name, zone.name)
    end

    private_class_method :label_for, :localized_name
  end
end
