# Pin npm packages by running ./bin/importmap

pin "application"
pin "pwa"
pin "dashboard_sidebar"
pin "pet_photo_preview"
pin "pet_gallery"
pin "pet_gallery_upload"
pin "pet_gallery_sortable"
pin "pet_gallery_keyboard"
pin "pet_main_photo"
pin "pet_profile_photo_zoom"
pin "journal_event_wizard"
pin "document_file_preview"
pin "public_pettag_location"
pin "notification_channels"
pin "account_profile"
pin "public_access_copy"
pin "birthday_greeting"
